/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.util.*;
import java.io.File;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
 import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.mail.*;
import javax.mail.internet.*;
import javax.activation.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author iti
 */
public class LIBRARYMANAGEMENT extends javax.swing.JFrame {
    /**
     * Creates new form LIBRARYMANAGEMENT
     */
    String sub=" ";
String l=" ";
 String X=" ";
 String J=" ";
 String f=" ";
                  int Y,sum1=0;
                  table b1=null;
                  listsql n= null;
 Addcategory MN= new Addcategory();   
ADDBOOK HJ= new ADDBOOK();
 public LIBRARYMANAGEMENT() {
      b1 = new table();
   n=new listsql();
  
      
      initComponents();

            Y=0;
          cost.setEditable(false);
           Drop.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
         jLabel6.setVisible(false);
          jLabel7.setVisible(false);
          Title.setVisible(false);
         author.setVisible(false);
     Publisher.setVisible(false);
          Edition.setVisible(false);
         cost.setVisible(false);
         jButton1.setVisible(false);
         jButton4.setVisible(false);
         jButton5.setVisible(false);       
    }
             
/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        author = new javax.swing.JTextField();
        Publisher = new javax.swing.JTextField();
        Edition = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cost = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Title = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        Drop = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        Type = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jScrollPane1.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Publisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PublisherActionPerformed(evt);
            }
        });

        Edition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditionActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Book type");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Book author");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Publisher");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Edition");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Find");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel5.setText("                                                                                     Agile Book Depot");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Cost");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Book Tittle");

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("Payment Reciept");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("Show Bill");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        Drop.setToolTipText("");
        Drop.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                DropItemStateChanged(evt);
            }
        });
        Drop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DropActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Category");

        Type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "entertainment", "education" }));
        Type.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                TypeItemStateChanged(evt);
            }
        });
        Type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Add Category ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setText("Add Book");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Show Category");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 1302, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cost, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)
                    .addComponent(author)
                    .addComponent(Publisher)
                    .addComponent(Edition)
                    .addComponent(Title)
                    .addComponent(Drop, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Type, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118)
                .addComponent(jButton3)
                .addGap(98, 98, 98)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(419, 419, 419))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(Type, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Drop, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(author, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Publisher, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)
                        .addComponent(jLabel6)
                        .addGap(129, 129, 129))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Edition, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addComponent(cost, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(117, 117, 117))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditionActionPerformed

    private void PublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PublisherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PublisherActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String s, Booktitle,author2,Publisher2,Edition2;
int a,b;

Booktitle=Title.getText();
author2=author.getText();
Publisher2=Publisher.getText();
Edition2=Edition.getText();
l=J;
if("entertainment".equals(J))
{
    Connection con=null;
    Statement st=null;
    ResultSet rs=null;
    
    try
    {
        Class.forName("com.mysql.jdbc.Driver");
          System.out.println("Driver Load");
          con=DriverManager.getConnection("jdbc:mysql://localhost:3306/entertainment","root","");
          System.out.println("connection established");
          st=con.createStatement();
        
         s="select * from "+sub+" Where BookTitle='"+Booktitle+"'And Author='"+author2+"'And Publisher ='"+Publisher2+"' And Edition ='"+Edition2+"'";
     
         
          rs=st.executeQuery(s) ;
          System.out.println(rs);
          if(rs.next())   
          {
              a=rs.getInt(6);
              if(a!=0)
              {
                 
                  X=rs.getString(1);
                  Y=rs.getInt(5);
            cost.setText(rs.getString(5));
                                a=a-1;
                                     int c;
        c=JOptionPane.showConfirmDialog(rootPane, "Do You Want to update This Record ? ");
          if(c==0)
          {   
          b1.add(this);
          
   
   sum1=sum1+Y;
   System.out.println(" "+X+" "+Y+" "+sum1);
   
   n.bill(this);
      
        int  i;
        i=JOptionPane.showConfirmDialog(rootPane, "Do You Want To Buy More Books? ");
if(i==0)
{
    
           Title.setText(" ");
            Publisher.setText(" ");
            
                    Edition.setText(" ");
                    cost.setText(" ");
   
         
         Drop.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
         jLabel6.setVisible(false);
          jLabel7.setVisible(false);
          Title.setVisible(false);
         author.setVisible(false);
     Publisher.setVisible(false);
          Edition.setVisible(false);
         cost.setVisible(false);
         jButton1.setVisible(false);
         jButton4.setVisible(false);
         jButton5.setVisible(false);
                   
}


 
          
       
              s="update entertainment_"+sub+" set  Avl_Books ='" + a + "' WHERE BookTitle='" +  Booktitle +"'";
              System.out.println("497"+s);  
           st.executeUpdate(s);
                           
            

         
          
         }
          else {
              JOptionPane.showMessageDialog(rootPane, "your record is not  updated");
          }
          
                
          }
              else
              {JOptionPane.showMessageDialog(rootPane, "Book Out Of Stock ");
          } }
          else{
                JOptionPane.showMessageDialog(rootPane, "Your Record Not Found !!!! ");
          }
        }
    
     catch(ClassNotFoundException e){
                System.out.println("Driver not loaded"+e);
     }
      catch(SQLException e){
                System.out.println("Driver not loaded"+e);
     }
     finally
             {
                 try
                 {
                  if(con!=null)
                     {
                     con.close();
                     }
                     if(st!=null)
                     {
                     st.close();
                     
                     }
                     if(rs!=null)
                     {
                     rs.close();
                     }
                 }
                     catch(Exception e1)
                     {
                     
                     }
             }   
}
else
{
    Connection con=null;
    Statement st=null;
    ResultSet rs=null;
    
    try
    {
        Class.forName("com.mysql.jdbc.Driver");
          System.out.println("Driver Load");
          con=DriverManager.getConnection("jdbc:mysql://localhost:3306/study","root","");
          System.out.println("connection established");
          st=con.createStatement();
        
         s="select * from "+sub+" where BookTitle='"+Booktitle+"'And Author='"+author2+"'And Publisher ='"+Publisher2+"'And Edition ='"+Edition2;
     
         
          rs=st.executeQuery(s);
          System.out.println(rs);
          if(rs.next())   
          {
              a=rs.getInt(6);
              if(a!=0)
              {
                 
                  X=rs.getString(1);
                  Y=rs.getInt(5);
            cost.setText(rs.getString(5));
                                a=a-1;
                                     int c;
        c=JOptionPane.showConfirmDialog(rootPane, "Do You Want to update This Record ? ");
                     
                          
          if(c==0)
          {   
          b1.add(this);
         
   sum1=sum1+Y;
      
        int  i;
        i=JOptionPane.showConfirmDialog(rootPane, "Do You Want To Buy More Books? ");
if(i==0)
{
    
           Title.setText(" ");
            Publisher.setText(" ");
            
                    Edition.setText(" ");
                    cost.setText(" ");
   
         
         Drop.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
         jLabel6.setVisible(false);
          jLabel7.setVisible(false);
          Title.setVisible(false);
         author.setVisible(false);
     Publisher.setVisible(false);
          Edition.setVisible(false);
         cost.setVisible(false);
         jButton1.setVisible(false);
         jButton4.setVisible(false);
         jButton5.setVisible(false);
              s="update  entertainment."+sub+" set  Avl_Books ='" + a + " ' WHERE BookTitle= '" +  Booktitle + "'";
              System.out.println(s);
           st.executeUpdate(s);     
}          
    
          
         
          
         }
          else {
              JOptionPane.showMessageDialog(rootPane, "your record is not  updated");
          }
          
                
          }
              else
              {JOptionPane.showMessageDialog(rootPane, "Book Out Of Stock ");
          } }
          else{
                JOptionPane.showMessageDialog(rootPane, "Your Record Not Found !!!! ");
          }
        }
    
     catch(ClassNotFoundException e){
                System.out.println("Driver not loaded"+e);
     }
      catch(SQLException e){
                System.out.println("Driver not loaded"+e);
     }
     finally
             {
                 try
                 {
                  if(con!=null)
                     {
                     con.close();
                     }
                     if(st!=null)
                     {
                     st.close();
                     
                     }
                     if(rs!=null)
                     {
                     rs.close();
                     }
                 }
                     catch(Exception e1)
                     {
                     
                     }
             }   
}

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
b1.show(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
n.show();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void DropItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_DropItemStateChanged
        sub=(String)Drop.getSelectedItem();
        
      


    }//GEN-LAST:event_DropItemStateChanged

    private void TypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_TypeItemStateChanged
    J=(String)Type.getSelectedItem();
        
    }//GEN-LAST:event_TypeItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    J=(String)Type.getSelectedItem();
        Drop.setVisible(true);
        jLabel2.setVisible(true);
        jLabel3.setVisible(true);
        jLabel4.setVisible(true);
         jLabel6.setVisible(true);
          jLabel7.setVisible(true);
          Title.setVisible(true);
         author.setVisible(true);
     Publisher.setVisible(true);
          Edition.setVisible(true);
         cost.setVisible(true);
         jButton1.setVisible(true);
         jButton4.setVisible(true);
         jButton5.setVisible(true);
          f="show tables;";
    Connection con=null;
    Statement st=null;
    ResultSet rs=null;
    System.out.print(f);
 
if("entertainment".equals(J))
{
    
    try
    {
        Class.forName("com.mysql.jdbc.Driver");
          System.out.println("Driver Load");
          con=DriverManager.getConnection("jdbc:mysql://localhost:3306/entertainment","root","");
          System.out.println("connection established");
          st=con.createStatement();

          int i=1;
          rs=st.executeQuery("show tables");
          System.out.println(rs);
          while(rs.next())   
          {
        Drop.addItem(rs.getString(1));
      
      System.out.print(rs.getString(1));
      i++;
          } 
          
        }
    
     catch(ClassNotFoundException e){
                System.out.println("Driver not loaded"+e);
     }
      catch(SQLException e){
                System.out.println("Driver not loaded"+e);
     }
     finally
             {
                 try
                 {
                  if(con!=null)
                     {
                     con.close();
                     }
                     if(st!=null)
                     {
                     st.close();
                     
                     }
                     if(rs!=null)
                     {
                     rs.close();
                     }
                 }
                     catch(Exception e1)
                     {
                     
                     }
             }                  } 
if("education".equals(J))
{
    
    try
    {
        Class.forName("com.mysql.jdbc.Driver");
          System.out.println("Driver Load");
          con=DriverManager.getConnection("jdbc:mysql://localhost:3306/education","root","");
          System.out.println("connection established");
          st=con.createStatement();

          int i=1;
          rs=st.executeQuery("show tables");
          System.out.println(rs);
          while(rs.next())   
          {
        Drop.addItem(rs.getString(1));
      
      System.out.print(rs.getString(1));
      i++;
          } 
          
        }
    
     catch(ClassNotFoundException e){
                System.out.println("Driver not loaded"+e);
     }
      catch(SQLException e){
                System.out.println("Driver not loaded"+e);
     }
     finally
             {
                 try
                 {
                  if(con!=null)
                     {
                     con.close();
                     }
                     if(st!=null)
                     {
                     st.close();
                     
                     }
                     if(rs!=null)
                     {
                     rs.close();
                     }
                 }
                     catch(Exception e1)
                     {
                     
                     }
             }                  } 
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeActionPerformed

    }//GEN-LAST:event_TypeActionPerformed

    private void DropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DropActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
MN.show();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
HJ.show();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LIBRARYMANAGEMENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LIBRARYMANAGEMENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LIBRARYMANAGEMENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LIBRARYMANAGEMENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {             
                new Login().setVisible(true);
                new LIBRARYMANAGEMENT().setVisible(false);               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Drop;
    private javax.swing.JTextField Edition;
    private javax.swing.JTextField Publisher;
    private javax.swing.JTextField Title;
    private javax.swing.JComboBox Type;
    private javax.swing.JTextField author;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField cost;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}